[book]
title = "Inkling"
authors = ["Petter Johansson"]
description = "User guide for `inkling`"
language = "en"
multilingual = false
src = "src"

[output.html]
theme = "src/theme"
curly-quotes = true
default_theme = "rust"

[output.html.fold]
enable = false

[output.html.playground]
editable = false
copyable = false
copy-js = true
line-numbers = false

[rust]
edition = "2018"
